CREATE DATABASE hospital;

CREATE TABLE medical_histories (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    admitted_at TIMESTAMP,
    patient_id INT,
    status VARCHAR,
    PRIMARY KEY(id)
);

CREATE TABLE patients (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR,
    date_of_birth DATE,
    PRIMARY KEY(id)
);
